### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GrumPHP\Task\AbstractExternalTask::__construct() must be an instance of GrumPHP\Process\ProcessBuilder, none given

### ISSUE THREAD

**Issue by cschalenborgh** [phpro/grumphp#342]
| Q               | A
| --------------- | ---
| Version         | "phpro/grumphp": "^0.11.4" (grumphp -v doesn't work anymore)
| Bug?            | maybe
| New feature?    | no
| Question?       | yes

I'm not sure what happened but after installing my repo on a new computer and setting everything up again, I'm getting this error:

```
./vendor/bin/grumphp run
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GrumPHP\Task\AbstractExternalTask::__construct() must be an instance of GrumPHP\Process\ProcessBuilder, none given in /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php:31
Stack trace:
#0 [internal function]: GrumPHP\Task\AbstractExternalTask->__construct(Object(GrumPHP\Configuration\GrumPHP))
#1 /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php(892): ReflectionClass->newInstanceArgs(Array)
#2 /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php(443): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'task.git.confli...')
#3 /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php(949): Symfony\Component\DependencyInjection\ContainerBuilder->get('task.git.confli...', 1)
#4 /Users/Username/Sites/myproject/vendor/symfony/dependency-in in /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php on line 31

Fatal error: Uncaught TypeError: Argument 2 passed to GrumPHP\Task\AbstractExternalTask::__construct() must be an instance of GrumPHP\Process\ProcessBuilder, none given in /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php on line 31

TypeError: Argument 2 passed to GrumPHP\Task\AbstractExternalTask::__construct() must be an instance of GrumPHP\Process\ProcessBuilder, none given in /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php on line 31

Call Stack:
    0.0003     355248   1. {main}() /Users/Username/Sites/myproject/vendor/phpro/grumphp/bin/grumphp:0
    0.0168    2920936   2. GrumPHP\Console\Application->__construct() /Users/Username/Sites/myproject/vendor/phpro/grumphp/bin/grumphp:30
    0.1765    7592856   3. Symfony\Component\Console\Application->__construct() /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Console/Application.php:55
    0.1767    7614000   4. GrumPHP\Console\Application->getDefaultHelperSet() /Users/Username/Sites/myproject/vendor/symfony/console/Application.php:83
    0.1787    7834768   5. Symfony\Component\DependencyInjection\ContainerBuilder->get() /Users/Username/Sites/myproject/vendor/phpro/grumphp/src/Console/Application.php:131
    0.1787    7834808   6. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:443
    0.2016    9463088   7. Symfony\Component\DependencyInjection\ContainerBuilder->callMethod() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:910
    0.2016    9463896   8. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:1137
    0.2016    9463896   9. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:946
    0.2016    9463896  10. Symfony\Component\DependencyInjection\ContainerBuilder->get() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:949
    0.2016    9463944  11. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:443
    0.2018    9472640  12. ReflectionClass->newInstanceArgs() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:892
    0.2018    9472752  13. GrumPHP\Task\AbstractExternalTask->__construct() /Users/Username/Sites/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php:892

```

Any ideas what's going on and how I can fix this?

**Comment by jyggen** [comment]
See #340.

**Comment by cschalenborgh** [comment]
I can't fix it with what @veewee's suggesting, but disabling the git_conflict task does work for me.

**Comment by cerw** [comment]
I am still getting these but only in Linux (not Mac) 

```
PHP Fatal error:  Uncaught TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /builds/sls/Community/vendor/symfony/process/ProcessBuilder.php on line 274 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:141
Stack trace:
#0 /builds/sls/Community/vendor/symfony/process/ProcessBuilder.php(274): Symfony\Component\Process\Process->__construct(Array, NULL, Array, NULL, 60, NULL)
#1 /builds/sls/Community/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(182): Symfony\Component\Process\ProcessBuilder->getProcess()
#2 /builds/sls/Community/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(137): GrumPHP\Composer\GrumPHPPlugin->runGrumPhpCommand('configure')
#3 [internal function]: GrumPHP\Composer\GrumPHPPlugin->runScheduledTasks(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local/bin in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 141

Fatal error: Uncaught TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /builds/sls/Community/vendor/symfony/process/ProcessBuilder.php on line 274 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:141
Stack trace:
#0 /builds/sls/Community/vendor/symfony/process/ProcessBuilder.php(274): Symfony\Component\Process\Process->__construct(Array, NULL, Array, NULL, 60, NULL)
#1 /builds/sls/Community/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(182): Symfony\Component\Process\ProcessBuilder->getProcess()
#2 /builds/sls/Community/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(137): GrumPHP\Composer\GrumPHPPlugin->runGrumPhpCommand('configure')
#3 [internal function]: GrumPHP\Composer\GrumPHPPlugin->runScheduledTasks(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local/bin in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 141
ERROR: Job failed: exit code 1
```

Here is my grumphp.yml

```
parameters:
    git_dir: .
    bin_dir: "./vendor/bin"
    stop_on_failure: true
    process_timeout: 180
    tasks:
      phpcs:
          standard: PSR2
          show_warnings: false
          ignore_patterns: [./tests, ./resources/*, ./database, ./bootstrap, ./public, ./config/]
      # phpunit:
      # git_commit_message:
      # git_conflict:
      # gulp:
      jsonlint:
      phplint:
      git_blacklist:
                  keywords:
                      - "die("
                      - " dd("
                      - "var_dump("
                      - "exit;"
                  triggered_by: [php]
      composer:
        file: ./composer.json

```

**Comment by TFarla** [comment]
Did you solve the `TypeError: Argument 6 passed to` issue? The same error occurs on my ubuntu xenial php 7.0 machine

**Comment by cerw** [comment]
@TFarla in my Docker testing image i am removing grumphp before runnign tests that;s the only thing that fixed it.

**Comment by TFarla** [comment]
Guess I will do the same and remove the dependency during CI. Thanks for the suggestion.

**Comment by veewee** [comment]
Lets continue the `TypeError: Argument 6 passed to ` dicussion in #414. It's a completely different issue.
