### ISSUE TITLE
Cannot run grumphp

### ISSUE THREAD

**Issue by Nek-** [phpro/grumphp#366]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | yes
| New feature?    | no

**My configuration**
NONE

**Steps to reproduce:**
```sh
# Generate empty folder
git clone git@github.com:symfony/symfony-demo.git
cd grumphp
composer require --dev phpro/grumphp

php ./vendor/bin/grumphp configure
```

**Result:**
```
php ./vendor/bin/grumphp configure
PHP Fatal error:  Uncaught Error: Class 'ProxyManager\Configuration' not found in /Users/veber/Projects/Tests/grumphp-test/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php:36
Stack trace:
#0 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Configuration/ContainerFactory.php(28): Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator->__construct()
#1 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Console/Application.php(157): GrumPHP\Configuration\ContainerFactory::buildFromConfiguration('/Users/veber/Pr...')
#2 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Console/Application.php(57): GrumPHP\Console\Application->getContainer()
#3 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/bin/grumphp(30): GrumPHP\Console\Application->__construct()
#4 {main}
  thrown in /Users/veber/Projects/Tests/grumphp-test/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php on line 36

Fatal error: Uncaught Error: Class 'ProxyManager\Configuration' not found in /Users/veber/Projects/Tests/grumphp-test/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php:36
Stack trace:
#0 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Configuration/ContainerFactory.php(28): Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator->__construct()
#1 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Console/Application.php(157): GrumPHP\Configuration\ContainerFactory::buildFromConfiguration('/Users/veber/Pr...')
#2 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/src/GrumPHP/Console/Application.php(57): GrumPHP\Console\Application->getContainer()
#3 /Users/veber/Projects/Tests/grumphp-test/vendor/phpro/grumphp/bin/grumphp(30): GrumPHP\Console\Application->__construct()
#4 {main}
  thrown in /Users/veber/Projects/Tests/grumphp-test/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php on line 36
```

**Comment by veewee** [comment]
@Nek-, Thanks for reporting!
You can solve this issue by adding:
```
composer require ocramius/proxy-manager
```

Strange issue: it is required by GrumPHP but doesn't get installed by composer. 
Will have to dive into the composer logs to see why it doesn't get installed.

**Comment by veewee** [comment]
@Nek-,

I've investigated this further en the issue is the hardcoded php version in the symfony-demo composer file:
https://github.com/symfony/symfony-demo/blob/master/composer.json#L62
```
    "config": {
        "platform": {
            "php": "5.5.9"
        }
},
```

This is forcing grumphp to install version 0.9.6:
```
$ composer require --dev phpro/grumphp
...
Using version ^0.9.6 for phpro/grumphp
...
```

When I try to install latest:

```sh
$ composer require --dev phpro/grumphp:v0.11.6
  Problem 1
    - Installation request for phpro/grumphp v0.11.6 -> satisfiable by phpro/grumphp[v0.11.6].
    - phpro/grumphp v0.11.6 requires php >=5.6.0 -> your PHP version (5.6.29) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
```

You can probably install it with the `--ignore-platform-reqs` option or by removing the php version from the platform config.

As of version 0.10.0 we've dropped PHP 5.5 support:
https://github.com/phpro/grumphp/releases/tag/v0.10.0

In version 0.10.2 we've resolved the issue of the proxy-manager not being installed during symfony/symfony:
https://github.com/phpro/grumphp/releases/tag/v0.10.2
https://github.com/phpro/grumphp/issues/240

As you can see, we cannot resolve this issue on our side. Since the demo is loading Symfony 3.3, it might be a good idea to bump that platform PHP version in the symfony-demo package.

I hope this fixes your issue.

**Comment by Nek-** [comment]
@veewee oh ! Thank you. And sorry for the wrong issue.

**Comment by Nek-** [comment]
@veewee do you accept a contribution to fix it?

**Comment by veewee** [comment]
@Nek-: Sure, if it gets fixed in an acceptable way :)
