### ISSUE TITLE
Fatal error when installing to a Laravel 5.5 project

### ISSUE THREAD

**Issue by lasselehtinen** [phpro/grumphp#420]
| Q               | A
| --------------- | ---
| Version         | `0.12.0`
| Bug?            | yes
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes
| Related tickets | #414

I am getting the following fatal error when trying to include grumphp in the latest version of Laravel (5.5.19).

**Steps to reproduce:**
```sh
# Install laraver
composer create-project --prefer-dist laravel/laravel demo
cd demo
composer require --dev phpro/grumphp
```

**Result:**
```
...
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
PHP Fatal error:  Uncaught TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /home/lasleh/Code/demo/vendor/symfony/process/ProcessBuilder.php on line 270 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:141
Stack trace:
#0 /home/lasleh/Code/demo/vendor/symfony/process/ProcessBuilder.php(270): Symfony\Component\Process\Process->__construct(Array, NULL, Array, NULL, 60, NULL)
#1 /home/lasleh/Code/demo/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(182): Symfony\Component\Process\ProcessBuilder->getProcess()
#2 /home/lasleh/Code/demo/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(137): GrumPHP\Composer\GrumPHPPlugin->runGrumPhpCommand('configure')
#3 [internal function]: GrumPHP\Composer\GrumPHPPlugin->runScheduledTasks(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 141

Fatal error: Uncaught TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /home/lasleh/Code/demo/vendor/symfony/process/ProcessBuilder.php on line 270 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:141
Stack trace:
#0 /home/lasleh/Code/demo/vendor/symfony/process/ProcessBuilder.php(270): Symfony\Component\Process\Process->__construct(Array, NULL, Array, NULL, 60, NULL)
#1 /home/lasleh/Code/demo/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(182): Symfony\Component\Process\ProcessBuilder->getProcess()
#2 /home/lasleh/Code/demo/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(137): GrumPHP\Composer\GrumPHPPlugin->runGrumPhpCommand('configure')
#3 [internal function]: GrumPHP\Composer\GrumPHPPlugin->runScheduledTasks(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 141

```

**Comment by veewee** [comment]
Hi @lasselehtinen,

This is not something grumphp related. Check #414 for additional information.
